apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8s-worker-1
  storageClassName: postgres-sc
  local:
    path: /home/prajwal/postgres/pv-storage
  volumeMode: Filesystem